package iplAnalyzer;

public enum SortingEnums
{
   BATTING_AVERAGE,
   BATTING_STRIKE_RATE,
   BEST_STRIKE_RATE_WITH_6s_4s,
   SORT_ON_4s_AND_6s,
   BATTING_STRIKE_RATE_AND_AVERAGE,
   STRIKE_RATE_AND_RUNS,
   BOWLING_AVERAGE,
   BOWLING_STRIKE_RATE,
   SORT_ON_4w_AND_5w,
   WICKETS_AND_AVERAGE,
   BOWLING_ECONOMY,
   ALL_ROUNDER_IN_AVERAGE,
   ALL_ROUNDER, BOWLING_STRIKE_RATE_AND_AVERAGE
}
